language: php

sudo: false

matrix:
  include:
    - php: 5.4
      env: PROCESS_CODECLIMATE=true
    - php: 5.5
    - php: 5.6
    - php: nightly
    - php: hhvm

  allow_failures:
      - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --dev --prefer-lowest --prefer-dist

script: ./test/bin/ci.bash summary
